export interface Video {
  slug: string;
  title: string;
  description: string;
  youtubeId: string;
  thumbnail: string;
  publishedAt: string;
  duration: string;
  focusKeyword: string;
  category: string;
  views: string;
}

export const videos: Video[] = [
  {
    "slug": "yamuna-expressway-investment-2030-who-should-buy-who-should-avoid-future-price-p",
    "title": "Yamuna Expressway Investment 2030: Who Should Buy, Who Should Avoid & Future Price Prediction",
    "description": "Watch the full review of Yamuna Expressway Investment 2030: Who Should Buy, Who Should Avoid & Future Price Prediction by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines in Noida.",
    "youtubeId": "qWAgkIW6Mj0",
    "thumbnail": "https://img.youtube.com/vi/qWAgkIW6Mj0/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT19M35S",
    "focusKeyword": "yamuna expressway investment",
    "category": "Real Estate",
    "views": "25K views views"
  },
  {
    "slug": "crc-the-peridona-jaypee-greens-noida-why-this-is-noidas-most-exclusive-project",
    "title": "CRC The Peridona Jaypee Greens Noida | Why This Is Noida’s Most Exclusive Project?",
    "description": "Watch the full review of CRC The Peridona Jaypee Greens Noida | Why This Is Noida’s Most Exclusive Project? by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines in Noida.",
    "youtubeId": "pAs9OoMvjQE",
    "thumbnail": "https://i.ytimg.com/vi/pAs9OoMvjQE/hqdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT20M9S",
    "focusKeyword": "crc the peridona",
    "category": "Real Estate",
    "views": "18K views views"
  },
  {
    "slug": "noida-market-slowdown-effects-on-builders-sellers-buyers-in-2026",
    "title": "Noida Market Slowdown: Effects on Builders, Sellers & Buyers in 2026",
    "description": "Watch the full review of Noida Market Slowdown: Effects on Builders, Sellers & Buyers in 2026 by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines in Noida.",
    "youtubeId": "g2dN6stL3i0",
    "thumbnail": "https://img.youtube.com/vi/g2dN6stL3i0/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT10M51S",
    "focusKeyword": "noida market slowdown",
    "category": "Real Estate",
    "views": "15K views views"
  },
  {
    "slug": "max-estates-105-vs-max-estates-128-which-one-is-better",
    "title": "Max Estates 105 vs Max Estates 128 | Which One is Better?",
    "description": "Watch the full review of Max Estates 105 vs Max Estates 128 | Which One is Better? by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines in Noida.",
    "youtubeId": "qfwf1IcrlsI",
    "thumbnail": "https://img.youtube.com/vi/qfwf1IcrlsI/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT12M16S",
    "focusKeyword": "max estates 105",
    "category": "Real Estate",
    "views": "6.1K views views"
  },
  {
    "slug": "noida-property-market-reality-authority-builder-broker-buyer-truth",
    "title": "Noida Property Market Reality | Authority, Builder, Broker & Buyer Truth",
    "description": "Watch the full review of Noida Property Market Reality | Authority, Builder, Broker & Buyer Truth by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines in Noida.",
    "youtubeId": "YKWtYdh_4dQ",
    "thumbnail": "https://img.youtube.com/vi/YKWtYdh_4dQ/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT11M56S",
    "focusKeyword": "noida property market",
    "category": "Real Estate",
    "views": "6.5K views views"
  },
  {
    "slug": "eldeco-7-peaks-residences-omicron-1-greater-noida-3bhk-layout-analysis-investmen",
    "title": "Eldeco 7 Peaks Residences Omicron 1 Greater Noida | 3BHK Layout Analysis + Investment Potential",
    "description": "Watch the full review of Eldeco 7 Peaks Residences Omicron 1 Greater Noida | 3BHK Layout Analysis + Investment Potential by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines in Noida.",
    "youtubeId": "hCyx0D2_RzE",
    "thumbnail": "https://img.youtube.com/vi/hCyx0D2_RzE/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT14M2S",
    "focusKeyword": "eldeco 7 peaks",
    "category": "Real Estate",
    "views": "18K views views"
  },
  {
    "slug": "commercial-property-in-noida-builder-lease-vs-self-lease",
    "title": "Commercial Property in Noida: Builder Lease vs Self Lease",
    "description": "Watch the full review of Commercial Property in Noida: Builder Lease vs Self Lease by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines in Noida.",
    "youtubeId": "LJo0YtPpTnY",
    "thumbnail": "https://img.youtube.com/vi/LJo0YtPpTnY/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT12M30S",
    "focusKeyword": "commercial property in",
    "category": "Real Estate",
    "views": "8.2K views views"
  },
  {
    "slug": "godrej-arden-sigma-3-review-price-floor-plan-location-analysis",
    "title": "Godrej Arden Sigma 3 Review | Price, Floor Plan & Location Analysis",
    "description": "Watch the full review of Godrej Arden Sigma 3 Review | Price, Floor Plan & Location Analysis by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines in Noida.",
    "youtubeId": "tWk2i0WUqiY",
    "thumbnail": "https://img.youtube.com/vi/tWk2i0WUqiY/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT12M24S",
    "focusKeyword": "godrej arden sigma",
    "category": "Real Estate",
    "views": "11K views views"
  },
  {
    "slug": "commercial-investment-in-noida-builder-leased-vs-self-lease",
    "title": "Commercial investment in Noida | Builder Leased vs Self Lease ?",
    "description": "Watch the full review of Commercial investment in Noida | Builder Leased vs Self Lease ? by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines in Noida.",
    "youtubeId": "41xfVmmczUA",
    "thumbnail": "https://img.youtube.com/vi/41xfVmmczUA/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT12M38S",
    "focusKeyword": "commercial investment in",
    "category": "Real Estate",
    "views": "5K views views"
  },
  {
    "slug": "noida-property-market-2025-what-worked-what-failed",
    "title": "Noida Property Market 2025: What Worked & What Failed",
    "description": "Watch the full review of Noida Property Market 2025: What Worked & What Failed by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines in Noida.",
    "youtubeId": "xicR-MeU77g",
    "thumbnail": "https://img.youtube.com/vi/xicR-MeU77g/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT32M41S",
    "focusKeyword": "noida property market",
    "category": "Real Estate",
    "views": "17K views views"
  },
  {
    "slug": "exit-advice-on-3-residential-projects-in-noida-ace-terra-godrej-tropical-isle-an",
    "title": "Exit Advice on 3 Residential Projects in Noida  Ace Terra, Godrej Tropical Isle and Ace Hanei",
    "description": "Watch the full review of Exit Advice on 3 Residential Projects in Noida  Ace Terra, Godrej Tropical Isle and Ace Hanei by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines in Noida.",
    "youtubeId": "9iAnowOVwjo",
    "thumbnail": "https://img.youtube.com/vi/9iAnowOVwjo/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT11M47S",
    "focusKeyword": "exit advice on",
    "category": "Real Estate",
    "views": "28K views views"
  },
  {
    "slug": "experion-saatori-sector-151-noida-honest-review-investment-analysis",
    "title": "Experion Saatori Sector 151 Noida | Honest Review & Investment Analysis",
    "description": "Watch the full review of Experion Saatori Sector 151 Noida | Honest Review & Investment Analysis by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines in Noida.",
    "youtubeId": "gYfkP-0pi0o",
    "thumbnail": "https://img.youtube.com/vi/gYfkP-0pi0o/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT11M57S",
    "focusKeyword": "experion saatori sector",
    "category": "Real Estate",
    "views": "23K views views"
  },
  {
    "slug": "sobha-rivana-noida-extension-review-better-than-sobha-aurum-or-overpriced",
    "title": "Sobha Rivana Noida Extension Review Better Than Sobha Aurum or Overpriced?",
    "description": "Watch the full review of Sobha Rivana Noida Extension Review Better Than Sobha Aurum or Overpriced? by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines in Noida.",
    "youtubeId": "6P-wf8O5Or8",
    "thumbnail": "https://img.youtube.com/vi/6P-wf8O5Or8/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT11M34S",
    "focusKeyword": "sobha rivana noida",
    "category": "Real Estate",
    "views": "7.5K views views"
  },
  {
    "slug": "jacob-co-noida-indias-first-branded-residence-in-noida-m3m-x-jacob-co-ultra-luxu",
    "title": "Jacob & Co Noida | India’s First Branded Residence in Noida | M3M x Jacob & Co Ultra Luxury Review",
    "description": "Watch the full review of Jacob & Co Noida | India’s First Branded Residence in Noida | M3M x Jacob & Co Ultra Luxury Review by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines in Noida.",
    "youtubeId": "LRZV-H--Qlw",
    "thumbnail": "https://img.youtube.com/vi/LRZV-H--Qlw/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT11M27S",
    "focusKeyword": "jacob  co",
    "category": "Real Estate",
    "views": "12K views views"
  },
  {
    "slug": "lt-green-reserve-noida-price-detail-payment-plan-exit-policy-appreciation-prospe",
    "title": "L&T Green Reserve Noida price detail payment plan exit Policy & Appreciation Prospects",
    "description": "Watch the full review of L&T Green Reserve Noida price detail payment plan exit Policy & Appreciation Prospects by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines in Noida.",
    "youtubeId": "oecEN5Ng0-o",
    "thumbnail": "https://img.youtube.com/vi/oecEN5Ng0-o/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT13M5S",
    "focusKeyword": "lt green reserve",
    "category": "Real Estate",
    "views": "5.3K views views"
  },
  {
    "slug": "prestige-city-ghaziabad-4-month-update-new-phase-project-progress-explained",
    "title": "Prestige City Ghaziabad 4-Month Update | New Phase & Project Progress Explained",
    "description": "Watch the full review of Prestige City Ghaziabad 4-Month Update | New Phase & Project Progress Explained by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines in Noida.",
    "youtubeId": "ugD-yKaiV2U",
    "thumbnail": "https://img.youtube.com/vi/ugD-yKaiV2U/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT10M17S",
    "focusKeyword": "prestige city ghaziabad",
    "category": "Real Estate",
    "views": "8.5K views views"
  },
  {
    "slug": "lt-green-reserve-sector-128-noida-watch-this-video-before-you-buy-compete-buying",
    "title": "⁠L&T Green Reserve Sector 128 Noida - Watch this video before you buy ! Compete Buying Guide",
    "description": "Watch the full review of ⁠L&T Green Reserve Sector 128 Noida - Watch this video before you buy ! Compete Buying Guide by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines in Noida.",
    "youtubeId": "YL6j01ID38w",
    "thumbnail": "https://img.youtube.com/vi/YL6j01ID38w/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT9M1S",
    "focusKeyword": "lt green reserve",
    "category": "Real Estate",
    "views": "9.4K views views"
  },
  {
    "slug": "is-gaurs-yamuna-expressway-launch-a-worthy-or-overpriced",
    "title": "Is Gaur's Yamuna Expressway Launch a Worthy or Overpriced?",
    "description": "Watch the full review of Is Gaur's Yamuna Expressway Launch a Worthy or Overpriced? by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines in Noida.",
    "youtubeId": "qKtESl55t-8",
    "thumbnail": "https://img.youtube.com/vi/qKtESl55t-8/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT10M41S",
    "focusKeyword": "is gaurs yamuna",
    "category": "Real Estate",
    "views": "6.7K views views"
  },
  {
    "slug": "noida-expressways-top3-most-profitable-self-use-projects-in-2025-revealed",
    "title": "Noida Expressway's TOP3 Most PROFITABLE Self-Use Projects in 2025 Revealed",
    "description": "Watch the full review of Noida Expressway's TOP3 Most PROFITABLE Self-Use Projects in 2025 Revealed by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines in Noida.",
    "youtubeId": "tQlCLCmTe5g",
    "thumbnail": "https://img.youtube.com/vi/tQlCLCmTe5g/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT16M17S",
    "focusKeyword": "noida expressways top3",
    "category": "Real Estate",
    "views": "7.3K views views"
  },
  {
    "slug": "is-ace-the-nest-studio-apartments-and-ace-verde-on-yamuna-expressway-an-opportun",
    "title": "Is Ace The Nest Studio Apartments and Ace Verde on Yamuna Expressway an Opportunity or Huge Mistake?",
    "description": "Watch the full review of Is Ace The Nest Studio Apartments and Ace Verde on Yamuna Expressway an Opportunity or Huge Mistake? by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines in Noida.",
    "youtubeId": "Q54r9FzP6oA",
    "thumbnail": "https://img.youtube.com/vi/Q54r9FzP6oA/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT15M38S",
    "focusKeyword": "is ace the",
    "category": "Real Estate",
    "views": "10K views views"
  },
  {
    "slug": "is-panvel-the-new-future-of-mumbais-3o-real-estate-market-godrejcitypanvel",
    "title": "Is Panvel the NEW FUTURE of Mumbai's 3.O Real Estate Market? #GodrejCityPanvel",
    "description": "Watch the full review of Is Panvel the NEW FUTURE of Mumbai's 3.O Real Estate Market? #GodrejCityPanvel by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines in Noida.",
    "youtubeId": "HJ461VdqOQ8",
    "thumbnail": "https://img.youtube.com/vi/HJ461VdqOQ8/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT10M23S",
    "focusKeyword": "is panvel the",
    "category": "Real Estate",
    "views": "7.8K views views"
  },
  {
    "slug": "godrej-evergreen-square-apartments-in-hinjewadi-pune",
    "title": "Godrej Evergreen Square Apartments in Hinjewadi Pune",
    "description": "Watch the full review of Godrej Evergreen Square Apartments in Hinjewadi Pune by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines in Noida.",
    "youtubeId": "i3FOJ1ZX79Q",
    "thumbnail": "https://img.youtube.com/vi/i3FOJ1ZX79Q/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT6M35S",
    "focusKeyword": "godrej evergreen square",
    "category": "Real Estate",
    "views": "5.2K views views"
  },
  {
    "slug": "sobha-aurum-greater-noida-sector-36-or-prestige-city-indirapuram-which-one-is-be",
    "title": "Sobha Aurum Greater Noida Sector 36 OR Prestige City Indirapuram Which ONE IS BETTER for you ?",
    "description": "Watch the full review of Sobha Aurum Greater Noida Sector 36 OR Prestige City Indirapuram Which ONE IS BETTER for you ? by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines in Noida.",
    "youtubeId": "j3U6dH_TqC8",
    "thumbnail": "https://img.youtube.com/vi/j3U6dH_TqC8/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT10M59S",
    "focusKeyword": "sobha aurum greater",
    "category": "Real Estate",
    "views": "9.3K views views"
  },
  {
    "slug": "is-godrej-majesty-noida-extension-worthy-of-an-investment",
    "title": "Is Godrej Majesty Noida extension worthy of an Investment?",
    "description": "Watch the full review of Is Godrej Majesty Noida extension worthy of an Investment? by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines in Noida.",
    "youtubeId": "oL--4DULuS8",
    "thumbnail": "https://img.youtube.com/vi/oL--4DULuS8/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT11M2S",
    "focusKeyword": "is godrej majesty",
    "category": "Real Estate",
    "views": "4.7K views views"
  },
  {
    "slug": "is-ace-acreville-really-worth-the-high-price-of-13l-per-yard",
    "title": "Is ACE ACREVILLE Really Worth the HIGH Price of 1.3L per yard?",
    "description": "Watch the full review of Is ACE ACREVILLE Really Worth the HIGH Price of 1.3L per yard? by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines in Noida.",
    "youtubeId": "K-s0W7NJMrk",
    "thumbnail": "https://img.youtube.com/vi/K-s0W7NJMrk/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT11M12S",
    "focusKeyword": "is ace acreville",
    "category": "Real Estate",
    "views": "4.3K views views"
  },
  {
    "slug": "dasnac-yuva-studio-apartments-review-rental-reality-roi-investment-analysis",
    "title": "Dasnac Yuva Studio Apartments Review | Rental Reality, ROI & Investment Analysis",
    "description": "Watch the full review of Dasnac Yuva Studio Apartments Review | Rental Reality, ROI & Investment Analysis by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines in Noida.",
    "youtubeId": "q37-HJHFhGc",
    "thumbnail": "https://img.youtube.com/vi/q37-HJHFhGc/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT7M13S",
    "focusKeyword": "dasnac yuva studio",
    "category": "Real Estate",
    "views": "12K views views"
  },
  {
    "slug": "top-3-ready-to-move-flats-on-noida-expressway",
    "title": "Top 3 Ready to move flats on Noida Expressway",
    "description": "Watch the full review of Top 3 Ready to move flats on Noida Expressway by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines in Noida.",
    "youtubeId": "yXLifyXxDKc",
    "thumbnail": "https://img.youtube.com/vi/yXLifyXxDKc/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT11M43S",
    "focusKeyword": "top 3 ready",
    "category": "Real Estate",
    "views": "8.8K views views"
  },
  {
    "slug": "sobha-aurum-greater-noida-sector-36-is-it-worth-the-hype",
    "title": "Sobha Aurum Greater Noida Sector 36, Is it worth the hype ?",
    "description": "Watch the full review of Sobha Aurum Greater Noida Sector 36, Is it worth the hype ? by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines in Noida.",
    "youtubeId": "vhttyOmqcuQ",
    "thumbnail": "https://img.youtube.com/vi/vhttyOmqcuQ/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT14M25S",
    "focusKeyword": "sobha aurum greater",
    "category": "Real Estate",
    "views": "17K views views"
  },
  {
    "slug": "ats-province-d-olympia-vs-ace-estate-which-yamuna-expressway-township-is-better-",
    "title": "ATS Province D Olympia vs ACE Estate: Which Yamuna Expressway Township Is Better in 2025?",
    "description": "Watch the full review of ATS Province D Olympia vs ACE Estate: Which Yamuna Expressway Township Is Better in 2025? by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines in Noida.",
    "youtubeId": "WGZZIqeLoaU",
    "thumbnail": "https://img.youtube.com/vi/WGZZIqeLoaU/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT5M35S",
    "focusKeyword": "ats province d",
    "category": "Real Estate",
    "views": "20K views views"
  },
  {
    "slug": "purvanchal-sunbliss-22d-yamuna-expressway-secrets-for-best-investment",
    "title": "Purvanchal Sunbliss 22D Yamuna Expressway  Secrets For BEST Investment",
    "description": "Watch the full review of Purvanchal Sunbliss 22D Yamuna Expressway  Secrets For BEST Investment by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines in Noida.",
    "youtubeId": "g805jc8GKhU",
    "thumbnail": "https://img.youtube.com/vi/g805jc8GKhU/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT7M19S",
    "focusKeyword": "purvanchal sunbliss 22d",
    "category": "Real Estate",
    "views": "12K views views"
  },
  {
    "slug": "ska-estate-luxury-apartments-in-greater-noida-at-realistic-prices",
    "title": "SKA estate Luxury Apartments in Greater Noida at Realistic Prices",
    "description": "Watch the full review of SKA estate Luxury Apartments in Greater Noida at Realistic Prices by Property Saraansh. Learn about layouts, project specifications, location advantages, pricing, and possession timelines.",
    "youtubeId": "PbyXvIrful0",
    "thumbnail": "https://img.youtube.com/vi/PbyXvIrful0/maxresdefault.jpg",
    "publishedAt": "2025-02-05",
    "duration": "PT15M41S",
    "focusKeyword": "ska estate luxury",
    "category": "Real Estate",
    "views": "15K views"
  },
  {
    "slug": "ace-groups-new-residential-plots-at-yamuna-expressway-noida",
    "title": "Ace Groups New Residential Plots at Yamuna Expressway Noida",
    "description": "Residential Ace estate plots at Yamuna Expressway Noida  #aceestate #aceplots #aceacreville #aceyamunaexpressway #acegroup #plotsonyamunaexpressway #yamunapl...",
    "youtubeId": "RiwupPz-wmQ",
    "thumbnail": "https://img.youtube.com/vi/RiwupPz-wmQ/maxresdefault.jpg",
    "publishedAt": "2025-01-12",
    "duration": "PT6M33S",
    "focusKeyword": "ace groups new residential plo",
    "category": "Real Estate",
    "views": "10K+ views"
  },
  {
    "slug": "godrej-riverine-a-luxury-apartment-option-near-delhi",
    "title": "Godrej Riverine – A Luxury Apartment Option Near Delhi",
    "description": "Godrej Riverine Sector 44 Noida: Redefining Premium Living  For those seeking a blend of luxury, comfort, and modern living in the thriving city of Noida, Go...",
    "youtubeId": "Dfba98En7rk",
    "thumbnail": "https://img.youtube.com/vi/Dfba98En7rk/maxresdefault.jpg",
    "publishedAt": "2025-01-03",
    "duration": "PT6M23S",
    "focusKeyword": "godrej riverine – a luxury apa",
    "category": "Real Estate",
    "views": "10K+ views"
  },
  {
    "slug": "prestige-city-ghaziabad-launch-everything-you-need-to-know-n",
    "title": "Prestige City Ghaziabad Launch: Everything You Need to Know Now",
    "description": "Prestige City Indirapuram Ghaziabad – Everything You Need to Know NowWhen it comes to premium residential living, Prestige City Ghaziabad sets a new benchmar...",
    "youtubeId": "NAb2cM4Q-1I",
    "thumbnail": "https://img.youtube.com/vi/NAb2cM4Q-1I/maxresdefault.jpg",
    "publishedAt": "2024-12-16",
    "duration": "PT9M40S",
    "focusKeyword": "prestige city ghaziabad launch",
    "category": "Real Estate",
    "views": "10K+ views"
  },
  {
    "slug": "top-3-studio-apartments-in-noida-for-high-roi",
    "title": "Top 3 Studio Apartments in Noida for High ROI",
    "description": "Explore the top 3 studio apartments in Noida—#dasnacarc  #orion132 #FairfoxEON —that promise excellent rental returns and investment opportunities.Top 3 Stud...",
    "youtubeId": "_YKDglIq2Fg",
    "thumbnail": "https://img.youtube.com/vi/_YKDglIq2Fg/maxresdefault.jpg",
    "publishedAt": "2024-12-12",
    "duration": "PT7M41S",
    "focusKeyword": "top 3 studio apartments in noi",
    "category": "Real Estate",
    "views": "10K+ views"
  },
  {
    "slug": "legacy-by-gaurs-launches-dream-homes-at-unbeatable-prices",
    "title": "Legacy by Gaurs Launches Dream Homes at Unbeatable Prices",
    "description": "Legacy by Gaurs ultra luxury apartments in Jaypee greens noida#legacybygaur #gaurlegacy #gaurlegacy #gaurparichok #gaurisland #gaurnoida #gaurgreaternoidaLeg...",
    "youtubeId": "jFlFfLNOKx0",
    "thumbnail": "https://img.youtube.com/vi/jFlFfLNOKx0/maxresdefault.jpg",
    "publishedAt": "2024-11-25",
    "duration": "PT8M32S",
    "focusKeyword": "legacy by gaurs launches dream",
    "category": "Real Estate",
    "views": "10K+ views"
  },
  {
    "slug": "what-makes-ace-hanei-the-most-desired-3-and-4-bhk-in-noida",
    "title": "What Makes ACE Hanei the MOST Desired 3 and 4 BHK in Noida",
    "description": "ACE Hanei Noida Extension Sector-12 New Project Luxurious 3 &amp; 4 BHK#Acehanei #Acehaneisector12 #AceHaneiGreaterNoida #acegroup #noidarealty #noidaproperties ...",
    "youtubeId": "NQf0pS1cjPE",
    "thumbnail": "https://img.youtube.com/vi/NQf0pS1cjPE/maxresdefault.jpg",
    "publishedAt": "2024-11-14",
    "duration": "PT9M22S",
    "focusKeyword": "what makes ace hanei the most ",
    "category": "Real Estate",
    "views": "10K+ views"
  },
  {
    "slug": "taj-skyscape-noida-why-hnis-are-choosing-hotel-managed-resid",
    "title": "Taj Skyscape Noida | Why HNIs Are Choosing Hotel-Managed Residences Over Luxury Apartments",
    "description": "Taj Hotel Branded Residences Coming to Noida Expressway Collab with Gulshan Group | The G by Gulshan group 5 Star Presidential Apartment Suites in Noida |Big...",
    "youtubeId": "WTMe76bD6-I",
    "thumbnail": "https://img.youtube.com/vi/WTMe76bD6-I/maxresdefault.jpg",
    "publishedAt": "2024-10-25",
    "duration": "PT5M40S",
    "focusKeyword": "taj skyscape noida",
    "category": "Real Estate",
    "views": "10K+ views"
  },
  {
    "slug": "m3m-cullinan-and-max-estate-128-on-noida-expressway-are-the-",
    "title": "M3M Cullinan and Max estate 128 on Noida Expressway are The MOST Luxurious Apartments",
    "description": "Ultra Luxury Apartments Options on Noida Expressway M3M The Cullinan Noida and max estate 128#m3mnoida #maxestatenoida #m3mcullinan #m3mproperties #maxestate...",
    "youtubeId": "d89gA6WupxM",
    "thumbnail": "https://img.youtube.com/vi/d89gA6WupxM/maxresdefault.jpg",
    "publishedAt": "2024-10-10",
    "duration": "PT6M43S",
    "focusKeyword": "m3m cullinan and max estate 12",
    "category": "Real Estate",
    "views": "10K+ views"
  },
  {
    "slug": "further-clarity-on-prestige-city-ghaziabad-payment-plan-exit",
    "title": "Further Clarity on Prestige City Ghaziabad Payment Plan | Exit Plan | Better than Gaur NYC?",
    "description": "Prestige City Ghaziabad - Further clarification #prestigesiddharthvihar #prestigeproperty #prestigecity #prestigeindrapuram #prestigeghaziabad Are you curious ...",
    "youtubeId": "ux80FKaXqdg",
    "thumbnail": "https://img.youtube.com/vi/ux80FKaXqdg/maxresdefault.jpg",
    "publishedAt": "2024-09-27",
    "duration": "PT6M45S",
    "focusKeyword": "further clarity on prestige ci",
    "category": "Real Estate",
    "views": "10K+ views"
  },
  {
    "slug": "comparing-top-noida-studio-projects-eon-vs-orion-vs-m3m-vs-g",
    "title": "Comparing Top Noida Studio Projects - EON vs Orion vs M3M Vs Golden Palm",
    "description": "Studio Apartment - Brand New Pre-Launch option/EON Vs Orion/Dasnac Vs M3M/Zest Vs Golden Palm #dasnacarc #fairfoxeon #fairfoxnoida #M3Mtheline #m3mstudio #m3m...",
    "youtubeId": "vhbwRsbIO5c",
    "thumbnail": "https://img.youtube.com/vi/vhbwRsbIO5c/maxresdefault.jpg",
    "publishedAt": "2024-09-19",
    "duration": "PT7M25S",
    "focusKeyword": "comparing top noida studio pro",
    "category": "Real Estate",
    "views": "10K+ views"
  },
  {
    "slug": "prestige-city-ghaziabad-a-practical-review-by-property-saraa",
    "title": "Prestige City Ghaziabad - A Practical Review by Property Saraansh",
    "description": "OAKWOOD in the Prestige City Ghaziabad - A Practical Review by Property Saraansh #prestigesiddharthvihar #prestigeghaziabad #prestigecity #prestigeoakwood",
    "youtubeId": "qeOagu8B3Kc",
    "thumbnail": "https://img.youtube.com/vi/qeOagu8B3Kc/maxresdefault.jpg",
    "publishedAt": "2024-09-09",
    "duration": "PT8M54S",
    "focusKeyword": "prestige city ghaziabad",
    "category": "Real Estate",
    "views": "10K+ views"
  },
  {
    "slug": "want-to-buy-an-apartment-in-noida-things-you-should-consider",
    "title": "Want to buy an Apartment in Noida? Things you should consider!",
    "description": "Investing in an apartment in Noida can be an excellent decision, but it's crucial to consider several factors before making a purchase. As a rapidly developing...",
    "youtubeId": "WPmnUl3ru9U",
    "thumbnail": "https://img.youtube.com/vi/WPmnUl3ru9U/maxresdefault.jpg",
    "publishedAt": "2024-08-18",
    "duration": "PT8M33S",
    "focusKeyword": "want to buy an apartment in no",
    "category": "Real Estate",
    "views": "10K+ views"
  },
  {
    "slug": "i-compared-dasnac-arc-and-m3m-the-line-for-rental-income-her",
    "title": "I Compared Dasnac ARC and M3M The Line for Rental Income Here's What I Found",
    "description": "I Compared Dasnac ARC and M3M The Line for Rental Income Here's What I Found #m3mline #dasnacarc #m3mstudio #m3mtheline #dasnacyuva #dasnac124 #studioapartment...",
    "youtubeId": "rbgRjoP2KIU",
    "thumbnail": "https://img.youtube.com/vi/rbgRjoP2KIU/maxresdefault.jpg",
    "publishedAt": "2024-08-06",
    "duration": "PT7M5S",
    "focusKeyword": "i compared dasnac arc and m3m ",
    "category": "Real Estate",
    "views": "10K+ views"
  },
  {
    "slug": "is-samridhi-daksh-avenue-really-better-than-prateek-canary-f",
    "title": "Is Samridhi Daksh Avenue Really BETTER Than Prateek Canary For Investment",
    "description": "Sector 150 Noida Luxury Projects Samridhi Dakhsh Avenue Vs. Prateek Canary Discover the ultimate luxury living experience at Sector 150 Noida. Samridhi Dakhsh...",
    "youtubeId": "s6V6M2zApmI",
    "thumbnail": "https://img.youtube.com/vi/s6V6M2zApmI/maxresdefault.jpg",
    "publishedAt": "2024-07-14",
    "duration": "PT8M57S",
    "focusKeyword": "is samridhi daksh avenue reall",
    "category": "Real Estate",
    "views": "10K+ views"
  },
  {
    "slug": "plots-in-noida-top-factors-to-be-considered",
    "title": "Plots in Noida Top Factors to be considered",
    "description": "Investing in a plot in Noida can be a lucrative opportunity, but it's crucial to consider several factors before making a purchase. In this video explained all...",
    "youtubeId": "fvggntit8Dg",
    "thumbnail": "https://img.youtube.com/vi/fvggntit8Dg/maxresdefault.jpg",
    "publishedAt": "2024-07-05",
    "duration": "PT9M6S",
    "focusKeyword": "plots in noida top factors to ",
    "category": "Real Estate",
    "views": "10K+ views"
  },
  {
    "slug": "studio-apartments-in-noida-best-small-investment-on-noida-ex",
    "title": "Studio Apartments in Noida - Best Small investment on Noida Expressway",
    "description": "Studio Apartments in Noida - Best Small investment on Noida Expressway #eonstudio #orionstudio #orion132 #dasnacarc #dasnacyuva #dasnac124 Investing in a studio...",
    "youtubeId": "DidX6OywjW0",
    "thumbnail": "https://img.youtube.com/vi/DidX6OywjW0/maxresdefault.jpg",
    "publishedAt": "2024-06-28",
    "duration": "PT7M47S",
    "focusKeyword": "studio apartments in noida",
    "category": "Real Estate",
    "views": "10K+ views"
  },
  {
    "slug": "is-sector-150-noida-hidden-real-estate-gem",
    "title": "Is Sector 150 Noida's Hidden Real Estate Gem?",
    "description": "Which is the best place to buy a home in Noida? Is Sector 150 Noida's Hidden Real Estate Gem? #sector150noida #noidaexpressway #propertyinvestor #sportscityno...",
    "youtubeId": "1JFYaapc3eA",
    "thumbnail": "https://img.youtube.com/vi/1JFYaapc3eA/maxresdefault.jpg",
    "publishedAt": "2024-06-22",
    "duration": "PT4M51S",
    "focusKeyword": "is sector 150 noida's hidd",
    "category": "Real Estate",
    "views": "10K+ views"
  },
  {
    "slug": "gulshan-dynasty-sample-flat-tour-ready-to-move-in-4-bhk-ultr",
    "title": "Gulshan Dynasty Sample flat tour ready to move in 4 BHK Ultra Luxury Apartments",
    "description": "Gulshan Dynasty in Noida: 4 BHK Ultra Luxury Apartments on Noida Expressway #gulshandynasty #gulshangroup #ultraluxuryliving #propertyreview #realestateinves...",
    "youtubeId": "0crM1LCI8dk",
    "thumbnail": "https://img.youtube.com/vi/0crM1LCI8dk/maxresdefault.jpg",
    "publishedAt": "2024-06-17",
    "duration": "PT3M4S",
    "focusKeyword": "gulshan dynasty sample flat to",
    "category": "Real Estate",
    "views": "10K+ views"
  },
  {
    "slug": "top-5-residential-projects-on-noida-expressway",
    "title": "Top 5 Residential Projects on Noida Expressway",
    "description": "Top 5 Residential Projects on Noida Expressway: Looking for the best place to call home along the Noida Expressway? Check out this video showcasing the top 5 ...",
    "youtubeId": "LLYIqQZ9Qr8",
    "thumbnail": "https://img.youtube.com/vi/LLYIqQZ9Qr8/maxresdefault.jpg",
    "publishedAt": "2024-06-10",
    "duration": "PT5M42S",
    "focusKeyword": "top 5 residential projects on ",
    "category": "Real Estate",
    "views": "10K+ views"
  },
  {
    "slug": "best-commercial-property-on-noida-expressway-for-investment",
    "title": "Best Commercial Property on Noida Expressway for Investment",
    "description": "Best Commercial Property on Noida Expressway for Investment Noida Expressway has emerged as one of the most lucrative hubs for commercial real estate in Ind...",
    "youtubeId": "Hd7cHcVrBWE",
    "thumbnail": "https://img.youtube.com/vi/Hd7cHcVrBWE/maxresdefault.jpg",
    "publishedAt": "2024-05-28",
    "duration": "PT4M59S",
    "focusKeyword": "best commercial property on no",
    "category": "Real Estate",
    "views": "10K+ views"
  },
  {
    "slug": "max-estates-128-and-max-estates-360-your-gateway-to-luxury-l",
    "title": "Max Estates 128 and Max Estates 360: Your Gateway to Luxury Living",
    "description": "Max Estates 128 and Max Estates 360: Your Gateway to Luxury Living Are you looking for a home that combines luxury, comfort, and holistic living? Max Estates ...",
    "youtubeId": "P0qDqzgMcho",
    "thumbnail": "https://img.youtube.com/vi/P0qDqzgMcho/maxresdefault.jpg",
    "publishedAt": "2024-05-13",
    "duration": "PT4M32S",
    "focusKeyword": "max estates 128 and max estate",
    "category": "Real Estate",
    "views": "10K+ views"
  },
  {
    "slug": "will-yamuna-expressway-actually-boom-by-2030-yamunaexpressway-noidarealestate",
    "title": "Will Yamuna Expressway Actually Boom by 2030? #yamunaexpressway #noidarealestate",
    "description": "Will Yamuna Expressway Actually Boom by 2030? #yamunaexpressway #noidarealestate",
    "youtubeId": "fslL0ubv2O4",
    "thumbnail": "https://img.youtube.com/vi/fslL0ubv2O4/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT0M59S",
    "focusKeyword": "will yamuna expressway",
    "category": "Shorts",
    "views": "10K views"
  },
  {
    "slug": "crc-sublimis-success-now-crc-the-peridona-takes-over",
    "title": "CRC Sublimis Success ➝ Now CRC The Peridona Takes Over!",
    "description": "CRC Sublimis Success ➝ Now CRC The Peridona Takes Over!",
    "youtubeId": "Hh_ZPRycdKE",
    "thumbnail": "https://img.youtube.com/vi/Hh_ZPRycdKE/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT0M59S",
    "focusKeyword": "crc sublimis success",
    "category": "Shorts",
    "views": "771 views"
  },
  {
    "slug": "crc-the-flagship-noida-exclusivity-begins-here",
    "title": "CRC The Flagship noida exclusivity begins here",
    "description": "CRC The Flagship noida exclusivity begins here",
    "youtubeId": "aYa-PtBcXl4",
    "thumbnail": "https://img.youtube.com/vi/aYa-PtBcXl4/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT0M59S",
    "focusKeyword": "crc the flagship",
    "category": "Shorts",
    "views": "1K views"
  },
  {
    "slug": "how-does-the-same-land-price-double-in-noida-shorts",
    "title": "How Does the Same Land Price Double in Noida? #shorts",
    "description": "How Does the Same Land Price Double in Noida? #shorts",
    "youtubeId": "IDO0ymvDMN0",
    "thumbnail": "https://img.youtube.com/vi/IDO0ymvDMN0/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT0M59S",
    "focusKeyword": "how does the",
    "category": "Shorts",
    "views": "1.1K views"
  },
  {
    "slug": "sobha-rivana-noida-extension-review-shorts",
    "title": "Sobha Rivana Noida Extension Review #shorts",
    "description": "Sobha Rivana Noida Extension Review #shorts",
    "youtubeId": "HH_BLcXgyh8",
    "thumbnail": "https://img.youtube.com/vi/HH_BLcXgyh8/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT0M59S",
    "focusKeyword": "sobha rivana noida",
    "category": "Shorts",
    "views": "2.6K views"
  },
  {
    "slug": "eldeco-7-peaks-residences-full-honest-review-eldecogreaternoida",
    "title": "Eldeco 7 Peaks Residences | Full Honest Review #eldecogreaternoida",
    "description": "Eldeco 7 Peaks Residences | Full Honest Review #eldecogreaternoida",
    "youtubeId": "X-4FBRXMegE",
    "thumbnail": "https://img.youtube.com/vi/X-4FBRXMegE/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT0M59S",
    "focusKeyword": "eldeco 7 peaks",
    "category": "Shorts",
    "views": "8.6K views"
  },
  {
    "slug": "elie-saab-jacob-co-noida-vs-m3m-cullinan-resale-m3mnoida",
    "title": "Elie Saab & Jacob & Co Noida vs M3M Cullinan Resale? #m3mnoida",
    "description": "Elie Saab & Jacob & Co Noida vs M3M Cullinan Resale? #m3mnoida",
    "youtubeId": "bPvVo3fyY0g",
    "thumbnail": "https://img.youtube.com/vi/bPvVo3fyY0g/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT0M59S",
    "focusKeyword": "elie saab ",
    "category": "Shorts",
    "views": "2.2K views"
  },
  {
    "slug": "ace-estate-vs-ace-acreville-vs-ats-province-d-olympia-plots-on-yamuna-expressway",
    "title": "ACE Estate vs ACE Acreville vs ATS Province D Olympia Plots on Yamuna Expressway: Fresh or Resale?",
    "description": "ACE Estate vs ACE Acreville vs ATS Province D Olympia Plots on Yamuna Expressway: Fresh or Resale?",
    "youtubeId": "Xm0a4TfOIcs",
    "thumbnail": "https://img.youtube.com/vi/Xm0a4TfOIcs/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT0M59S",
    "focusKeyword": "ace estate vs",
    "category": "Shorts",
    "views": "6.5K views"
  },
  {
    "slug": "godrej-arden-review-godrejarden-shorts",
    "title": "Godrej Arden Review #godrejarden #shorts",
    "description": "Godrej Arden Review #godrejarden #shorts",
    "youtubeId": "vLKKclfcVvU",
    "thumbnail": "https://img.youtube.com/vi/vLKKclfcVvU/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT0M59S",
    "focusKeyword": "godrej arden review",
    "category": "Shorts",
    "views": "2.2K views"
  },
  {
    "slug": "builder-lease-vs-self-lease-which-is-best-for-your-noida-commercial-property-sho",
    "title": "Builder Lease vs Self Lease Which is BEST for Your Noida Commercial Property #shorts",
    "description": "Builder Lease vs Self Lease Which is BEST for Your Noida Commercial Property #shorts",
    "youtubeId": "j9WmfwO6R1A",
    "thumbnail": "https://img.youtube.com/vi/j9WmfwO6R1A/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT0M59S",
    "focusKeyword": "builder lease vs",
    "category": "Shorts",
    "views": "970 views"
  },
  {
    "slug": "ace-terra-investors-exit-shorts-aceterra",
    "title": "Ace Terra Investors Exit ? #shorts #aceterra",
    "description": "Ace Terra Investors Exit ? #shorts #aceterra",
    "youtubeId": "7W2HnVE_WyQ",
    "thumbnail": "https://img.youtube.com/vi/7W2HnVE_WyQ/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT0M59S",
    "focusKeyword": "ace terra investors",
    "category": "Shorts",
    "views": "2.2K views"
  },
  {
    "slug": "unable-to-exit-your-noida-property-investment-watch-this-first-propertysaraansh-",
    "title": "Unable to Exit Your Noida Property Investment? Watch This First  #propertysaraansh #noidarealty",
    "description": "Unable to Exit Your Noida Property Investment? Watch This First  #propertysaraansh #noidarealty",
    "youtubeId": "n3xQEmTDZS4",
    "thumbnail": "https://img.youtube.com/vi/n3xQEmTDZS4/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT0M59S",
    "focusKeyword": "unable to exit",
    "category": "Shorts",
    "views": "2.2K views"
  },
  {
    "slug": "experion-151-noida-honest-review-should-you-buy-here",
    "title": "Experion 151 Noida Honest Review | Should You Buy Here?",
    "description": "Experion 151 Noida Honest Review | Should You Buy Here?",
    "youtubeId": "GD1ax-NI1gY",
    "thumbnail": "https://img.youtube.com/vi/GD1ax-NI1gY/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT0M59S",
    "focusKeyword": "experion 151 noida",
    "category": "Shorts",
    "views": "2.7K views"
  },
  {
    "slug": "wishing-you-a-happy-diwali-team-property-saraansh-happydiwali",
    "title": "Wishing You a Happy Diwali Team Property Saraansh #happydiwali",
    "description": "Wishing You a Happy Diwali Team Property Saraansh #happydiwali",
    "youtubeId": "3uW5F19WXY0",
    "thumbnail": "https://img.youtube.com/vi/3uW5F19WXY0/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT0M59S",
    "focusKeyword": "wishing you a",
    "category": "Shorts",
    "views": "1.5K views"
  },
  {
    "slug": "lt-golf-course-apartments-sector-128-noida-expressway-reserve-green-eoi-started",
    "title": "L&T Golf Course Apartments Sector 128 Noida Expressway Reserve Green EOI Started",
    "description": "L&T Golf Course Apartments Sector 128 Noida Expressway Reserve Green EOI Started",
    "youtubeId": "I1O5bCqKcgs",
    "thumbnail": "https://img.youtube.com/vi/I1O5bCqKcgs/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT0M59S",
    "focusKeyword": "lt golf course",
    "category": "Shorts",
    "views": "5K views"
  },
  {
    "slug": "ace-the-nest-or-fairfox-eon-dasnac-arc-which-studio-apartment-wins-for-roi-locat",
    "title": "ACE The Nest or Fairfox EON, Dasnac ARC ? | Which Studio Apartment Wins for ROI & Location in 2025?",
    "description": "ACE The Nest or Fairfox EON, Dasnac ARC ? | Which Studio Apartment Wins for ROI & Location in 2025?",
    "youtubeId": "o1EvJ6eO9WI",
    "thumbnail": "https://img.youtube.com/vi/o1EvJ6eO9WI/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT0M59S",
    "focusKeyword": "ace the nest",
    "category": "Shorts",
    "views": "8.2K views"
  },
  {
    "slug": "godrej-evergreen-square-in-hinjewadi-pune-godrejevergreensquare-godrejhinjewadip",
    "title": "Godrej Evergreen Square in Hinjewadi Pune #godrejevergreensquare #godrejhinjewadipune",
    "description": "Godrej Evergreen Square in Hinjewadi Pune #godrejevergreensquare #godrejhinjewadipune",
    "youtubeId": "V0-CB-BHygo",
    "thumbnail": "https://img.youtube.com/vi/V0-CB-BHygo/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT0M59S",
    "focusKeyword": "godrej evergreen square",
    "category": "Shorts",
    "views": "2.5K views"
  },
  {
    "slug": "the-future-of-luxury-living-in-noida-revealed-jaypeegreens-camellias-dlfprivana",
    "title": "The Future of Luxury Living in NOIDA Revealed #jaypeegreens #camellias #dlfprivana",
    "description": "The Future of Luxury Living in NOIDA Revealed #jaypeegreens #camellias #dlfprivana",
    "youtubeId": "6hop-aVpJHs",
    "thumbnail": "https://img.youtube.com/vi/6hop-aVpJHs/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT0M59S",
    "focusKeyword": "the future of",
    "category": "Shorts",
    "views": "4K views"
  },
  {
    "slug": "sobha-36-greater-noida-eoi-process",
    "title": "Sobha 36 greater Noida EOI process",
    "description": "Sobha 36 greater Noida EOI process",
    "youtubeId": "ddl6kteX9Ms",
    "thumbnail": "https://img.youtube.com/vi/ddl6kteX9Ms/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT0M59S",
    "focusKeyword": "sobha 36 greater",
    "category": "Shorts",
    "views": "1.5K views"
  },
  {
    "slug": "oakwood-at-the-prestige-city-ghaziabad-prestigesiddharthvihar-oawoodprestige-pre",
    "title": "Oakwood At The Prestige City Ghaziabad #prestigesiddharthvihar #oawoodprestige #prestigeghaziabad",
    "description": "Oakwood At The Prestige City Ghaziabad #prestigesiddharthvihar #oawoodprestige #prestigeghaziabad",
    "youtubeId": "zhbuPaDFGqc",
    "thumbnail": "https://img.youtube.com/vi/zhbuPaDFGqc/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT0M59S",
    "focusKeyword": "oakwood at the",
    "category": "Shorts",
    "views": "3.4K views"
  },
  {
    "slug": "prestige-city-ghaziabad-rera-received-prestigesiddharthvihar-prestigeghaziabad",
    "title": "Prestige city Ghaziabad RERA Received #prestigesiddharthvihar #prestigeghaziabad",
    "description": "Prestige city Ghaziabad RERA Received #prestigesiddharthvihar #prestigeghaziabad",
    "youtubeId": "IAu1mHz5BPU",
    "thumbnail": "https://img.youtube.com/vi/IAu1mHz5BPU/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT0M59S",
    "focusKeyword": "prestige city ghaziabad",
    "category": "Shorts",
    "views": "3.8K views"
  },
  {
    "slug": "purvanchal-sunbliss-sector-22d-on-yamuna-expressway-pricing-and-pre-launch-detai",
    "title": "Purvanchal Sunbliss Sector 22D on Yamuna Expressway Pricing and Pre-Launch Details",
    "description": "Purvanchal Sunbliss Sector 22D on Yamuna Expressway Pricing and Pre-Launch Details",
    "youtubeId": "_KdW-ZbDDwg",
    "thumbnail": "https://img.youtube.com/vi/_KdW-ZbDDwg/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT0M59S",
    "focusKeyword": "purvanchal sunbliss sector",
    "category": "Shorts",
    "views": "5.8K views"
  },
  {
    "slug": "94-crore-luxury-4bhk-in-noida-that-sells-out-fast-luxuryhomes-noida",
    "title": "₹9.4 Crore Luxury 4BHK in Noida That Sells Out Fast #LuxuryHomes #Noida",
    "description": "₹9.4 Crore Luxury 4BHK in Noida That Sells Out Fast #LuxuryHomes #Noida",
    "youtubeId": "heHoAeyzVqI",
    "thumbnail": "https://img.youtube.com/vi/heHoAeyzVqI/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT0M59S",
    "focusKeyword": "94 crore luxury",
    "category": "Shorts",
    "views": "2.7K views"
  },
  {
    "slug": "wishing-entire-family-of-property-saraansh-a-very-happy-new-year-happynewyear-ne",
    "title": "Wishing entire Family of PROPERTY SARAANSH a Very Happy New Year ! #happynewyear #newyear2025",
    "description": "Wishing entire Family of PROPERTY SARAANSH a Very Happy New Year ! #happynewyear #newyear2025",
    "youtubeId": "XaJAvEMOY3c",
    "thumbnail": "https://img.youtube.com/vi/XaJAvEMOY3c/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT0M59S",
    "focusKeyword": "wishing entire family",
    "category": "Shorts",
    "views": "447 views"
  },
  {
    "slug": "prestige-city-ghaziabad-prestigecityghaziabad",
    "title": "Prestige City Ghaziabad #prestigecityghaziabad",
    "description": "Prestige City Ghaziabad #prestigecityghaziabad",
    "youtubeId": "p8eeYqhVUgY",
    "thumbnail": "https://img.youtube.com/vi/p8eeYqhVUgY/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT0M59S",
    "focusKeyword": "prestige city ghaziabad",
    "category": "Shorts",
    "views": "9.3K views"
  },
  {
    "slug": "prestige-siddharth-vihar-pre-launch-opportunity-prestigecity-prestigecityghaziab",
    "title": "Prestige Siddharth Vihar Pre Launch Opportunity #prestigecity #prestigecityghaziabad",
    "description": "Prestige Siddharth Vihar Pre Launch Opportunity #prestigecity #prestigecityghaziabad",
    "youtubeId": "sF4KdO4AzsM",
    "thumbnail": "https://img.youtube.com/vi/sF4KdO4AzsM/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT0M59S",
    "focusKeyword": "prestige siddharth vihar",
    "category": "Shorts",
    "views": "3.1K views"
  },
  {
    "slug": "orion-132-best-commercial-investment-noidaexpressway-commercialproperty-studioap",
    "title": "Orion 132 best commercial investment #noidaexpressway #commercialproperty #studioapartments",
    "description": "Orion 132 best commercial investment #noidaexpressway #commercialproperty #studioapartments",
    "youtubeId": "VMFJGlKdBD4",
    "thumbnail": "https://img.youtube.com/vi/VMFJGlKdBD4/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT0M59S",
    "focusKeyword": "orion 132 best",
    "category": "Shorts",
    "views": "7.2K views"
  },
  {
    "slug": "my-attitude-after-closing-10-deals-realtor-realtorsofinstagram-realestatemarket2",
    "title": "My attitude after closing 10 deals😛 #realtor #realtorsofinstagram  #realestatemarket2024 #realtors",
    "description": "My attitude after closing 10 deals😛 #realtor #realtorsofinstagram  #realestatemarket2024 #realtors",
    "youtubeId": "HDT3ksdZdCg",
    "thumbnail": "https://img.youtube.com/vi/HDT3ksdZdCg/maxresdefault.jpg",
    "publishedAt": "2026-06-11",
    "duration": "PT0M59S",
    "focusKeyword": "my attitude after",
    "category": "Shorts",
    "views": "975 views"
  }
];

export function getVideoBySlug(slug: string): Video | null {
  // Support both slug-only and slug-with-id
  const cleanSlug = slug.toLowerCase();
  return videos.find((v) => v.slug === cleanSlug || cleanSlug.endsWith(v.youtubeId.toLowerCase())) || null;
}
